// Mocks generated by Mockito 5.4.4 from annotations
// in drpharma_client/test/features/wallet/domain/usecases/wallet_usecases_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:drpharma_client/core/errors/failures.dart' as _i5;
import 'package:drpharma_client/features/wallet/domain/entities/wallet_entity.dart'
    as _i6;
import 'package:drpharma_client/features/wallet/domain/repositories/wallet_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [WalletRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockWalletRepository extends _i1.Mock implements _i3.WalletRepository {
  MockWalletRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.WalletEntity>> getWallet() =>
      (super.noSuchMethod(
        Invocation.method(
          #getWallet,
          [],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i6.WalletEntity>>.value(
                _FakeEither_0<_i5.Failure, _i6.WalletEntity>(
          this,
          Invocation.method(
            #getWallet,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.WalletEntity>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.WalletTransactionEntity>>>
      getTransactions({
    int? limit = 50,
    String? category,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #getTransactions,
              [],
              {
                #limit: limit,
                #category: category,
              },
            ),
            returnValue: _i4.Future<
                    _i2.Either<_i5.Failure,
                        List<_i6.WalletTransactionEntity>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.WalletTransactionEntity>>(
              this,
              Invocation.method(
                #getTransactions,
                [],
                {
                  #limit: limit,
                  #category: category,
                },
              ),
            )),
          ) as _i4.Future<
              _i2.Either<_i5.Failure, List<_i6.WalletTransactionEntity>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.PaymentInitResult>> initiateTopUp({
    required double? amount,
    required String? paymentMethod,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #initiateTopUp,
          [],
          {
            #amount: amount,
            #paymentMethod: paymentMethod,
          },
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i6.PaymentInitResult>>.value(
                _FakeEither_0<_i5.Failure, _i6.PaymentInitResult>(
          this,
          Invocation.method(
            #initiateTopUp,
            [],
            {
              #amount: amount,
              #paymentMethod: paymentMethod,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.PaymentInitResult>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.PaymentStatusResult>>
      checkPaymentStatus(String? reference) => (super.noSuchMethod(
            Invocation.method(
              #checkPaymentStatus,
              [reference],
            ),
            returnValue: _i4
                .Future<_i2.Either<_i5.Failure, _i6.PaymentStatusResult>>.value(
                _FakeEither_0<_i5.Failure, _i6.PaymentStatusResult>(
              this,
              Invocation.method(
                #checkPaymentStatus,
                [reference],
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, _i6.PaymentStatusResult>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.WalletTransactionEntity>> topUp({
    required double? amount,
    required String? paymentMethod,
    String? paymentReference,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #topUp,
          [],
          {
            #amount: amount,
            #paymentMethod: paymentMethod,
            #paymentReference: paymentReference,
          },
        ),
        returnValue: _i4
            .Future<_i2.Either<_i5.Failure, _i6.WalletTransactionEntity>>.value(
            _FakeEither_0<_i5.Failure, _i6.WalletTransactionEntity>(
          this,
          Invocation.method(
            #topUp,
            [],
            {
              #amount: amount,
              #paymentMethod: paymentMethod,
              #paymentReference: paymentReference,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.WalletTransactionEntity>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.WalletTransactionEntity>> withdraw({
    required double? amount,
    required String? paymentMethod,
    required String? phoneNumber,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #withdraw,
          [],
          {
            #amount: amount,
            #paymentMethod: paymentMethod,
            #phoneNumber: phoneNumber,
          },
        ),
        returnValue: _i4
            .Future<_i2.Either<_i5.Failure, _i6.WalletTransactionEntity>>.value(
            _FakeEither_0<_i5.Failure, _i6.WalletTransactionEntity>(
          this,
          Invocation.method(
            #withdraw,
            [],
            {
              #amount: amount,
              #paymentMethod: paymentMethod,
              #phoneNumber: phoneNumber,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.WalletTransactionEntity>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.WalletTransactionEntity>> payOrder({
    required double? amount,
    required String? orderReference,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #payOrder,
          [],
          {
            #amount: amount,
            #orderReference: orderReference,
          },
        ),
        returnValue: _i4
            .Future<_i2.Either<_i5.Failure, _i6.WalletTransactionEntity>>.value(
            _FakeEither_0<_i5.Failure, _i6.WalletTransactionEntity>(
          this,
          Invocation.method(
            #payOrder,
            [],
            {
              #amount: amount,
              #orderReference: orderReference,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.WalletTransactionEntity>>);
}
