// Mocks generated by Mockito 5.4.4 from annotations
// in drpharma_client/test/features/products/presentation/providers/products_notifier_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:drpharma_client/core/errors/failures.dart' as _i5;
import 'package:drpharma_client/features/products/domain/entities/product_entity.dart'
    as _i6;
import 'package:drpharma_client/features/products/domain/usecases/get_product_details_usecase.dart'
    as _i8;
import 'package:drpharma_client/features/products/domain/usecases/get_products_by_category_usecase.dart'
    as _i9;
import 'package:drpharma_client/features/products/domain/usecases/get_products_usecase.dart'
    as _i3;
import 'package:drpharma_client/features/products/domain/usecases/search_products_usecase.dart'
    as _i7;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetProductsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetProductsUseCase extends _i1.Mock
    implements _i3.GetProductsUseCase {
  MockGetProductsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.ProductEntity>>> call(
          {int? page = 1}) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
          {#page: page},
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, List<_i6.ProductEntity>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.ProductEntity>>(
          this,
          Invocation.method(
            #call,
            [],
            {#page: page},
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.ProductEntity>>>);
}

/// A class which mocks [SearchProductsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSearchProductsUseCase extends _i1.Mock
    implements _i7.SearchProductsUseCase {
  MockSearchProductsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.ProductEntity>>> call({
    required String? query,
    int? page = 1,
    int? perPage = 20,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
          {
            #query: query,
            #page: page,
            #perPage: perPage,
          },
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, List<_i6.ProductEntity>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.ProductEntity>>(
          this,
          Invocation.method(
            #call,
            [],
            {
              #query: query,
              #page: page,
              #perPage: perPage,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.ProductEntity>>>);
}

/// A class which mocks [GetProductDetailsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetProductDetailsUseCase extends _i1.Mock
    implements _i8.GetProductDetailsUseCase {
  MockGetProductDetailsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.ProductEntity>> call(int? productId) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [productId],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i6.ProductEntity>>.value(
                _FakeEither_0<_i5.Failure, _i6.ProductEntity>(
          this,
          Invocation.method(
            #call,
            [productId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.ProductEntity>>);
}

/// A class which mocks [GetProductsByCategoryUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetProductsByCategoryUseCase extends _i1.Mock
    implements _i9.GetProductsByCategoryUseCase {
  MockGetProductsByCategoryUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.ProductEntity>>> call({
    String? category,
    int? page = 1,
    int? perPage = 20,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
          {
            #category: category,
            #page: page,
            #perPage: perPage,
          },
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, List<_i6.ProductEntity>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.ProductEntity>>(
          this,
          Invocation.method(
            #call,
            [],
            {
              #category: category,
              #page: page,
              #perPage: perPage,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.ProductEntity>>>);
}
