// Mocks generated by Mockito 5.4.4 from annotations
// in drpharma_client/test/features/profile/data/repositories/profile_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:typed_data' as _i6;

import 'package:drpharma_client/core/network/api_client.dart' as _i2;
import 'package:drpharma_client/features/profile/data/datasources/profile_local_datasource.dart'
    as _i8;
import 'package:drpharma_client/features/profile/data/datasources/profile_remote_datasource.dart'
    as _i4;
import 'package:drpharma_client/features/profile/data/models/profile_model.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeApiClient_0 extends _i1.SmartFake implements _i2.ApiClient {
  _FakeApiClient_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeProfileModel_1 extends _i1.SmartFake implements _i3.ProfileModel {
  _FakeProfileModel_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ProfileRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockProfileRemoteDataSource extends _i1.Mock
    implements _i4.ProfileRemoteDataSource {
  MockProfileRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ApiClient get apiClient => (super.noSuchMethod(
        Invocation.getter(#apiClient),
        returnValue: _FakeApiClient_0(
          this,
          Invocation.getter(#apiClient),
        ),
      ) as _i2.ApiClient);

  @override
  _i5.Future<_i3.ProfileModel> getProfile() => (super.noSuchMethod(
        Invocation.method(
          #getProfile,
          [],
        ),
        returnValue: _i5.Future<_i3.ProfileModel>.value(_FakeProfileModel_1(
          this,
          Invocation.method(
            #getProfile,
            [],
          ),
        )),
      ) as _i5.Future<_i3.ProfileModel>);

  @override
  _i5.Future<_i3.ProfileModel> updateProfile(Map<String, dynamic>? data) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateProfile,
          [data],
        ),
        returnValue: _i5.Future<_i3.ProfileModel>.value(_FakeProfileModel_1(
          this,
          Invocation.method(
            #updateProfile,
            [data],
          ),
        )),
      ) as _i5.Future<_i3.ProfileModel>);

  @override
  _i5.Future<String> uploadAvatar(_i6.Uint8List? imageBytes) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadAvatar,
          [imageBytes],
        ),
        returnValue: _i5.Future<String>.value(_i7.dummyValue<String>(
          this,
          Invocation.method(
            #uploadAvatar,
            [imageBytes],
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<void> deleteAvatar() => (super.noSuchMethod(
        Invocation.method(
          #deleteAvatar,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [ProfileLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockProfileLocalDataSource extends _i1.Mock
    implements _i8.ProfileLocalDataSource {
  MockProfileLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<void> cacheProfile(_i3.ProfileModel? profile) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheProfile,
          [profile],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i3.ProfileModel?> getCachedProfile() => (super.noSuchMethod(
        Invocation.method(
          #getCachedProfile,
          [],
        ),
        returnValue: _i5.Future<_i3.ProfileModel?>.value(),
      ) as _i5.Future<_i3.ProfileModel?>);

  @override
  _i5.Future<void> clearProfile() => (super.noSuchMethod(
        Invocation.method(
          #clearProfile,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}
