// Mocks generated by Mockito 5.4.4 from annotations
// in drpharma_client/test/features/pharmacies/data/repositories/pharmacies_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:drpharma_client/core/network/api_client.dart' as _i2;
import 'package:drpharma_client/features/pharmacies/data/datasources/pharmacies_remote_datasource.dart'
    as _i4;
import 'package:drpharma_client/features/pharmacies/data/models/pharmacy_model.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeApiClient_0 extends _i1.SmartFake implements _i2.ApiClient {
  _FakeApiClient_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePharmacyModel_1 extends _i1.SmartFake implements _i3.PharmacyModel {
  _FakePharmacyModel_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [PharmaciesRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockPharmaciesRemoteDataSource extends _i1.Mock
    implements _i4.PharmaciesRemoteDataSource {
  MockPharmaciesRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ApiClient get apiClient => (super.noSuchMethod(
        Invocation.getter(#apiClient),
        returnValue: _FakeApiClient_0(
          this,
          Invocation.getter(#apiClient),
        ),
      ) as _i2.ApiClient);

  @override
  _i5.Future<List<_i3.PharmacyModel>> getPharmacies({
    int? page = 1,
    int? perPage = 20,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPharmacies,
          [],
          {
            #page: page,
            #perPage: perPage,
          },
        ),
        returnValue:
            _i5.Future<List<_i3.PharmacyModel>>.value(<_i3.PharmacyModel>[]),
      ) as _i5.Future<List<_i3.PharmacyModel>>);

  @override
  _i5.Future<List<_i3.PharmacyModel>> getNearbyPharmacies({
    required double? latitude,
    required double? longitude,
    double? radius,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getNearbyPharmacies,
          [],
          {
            #latitude: latitude,
            #longitude: longitude,
            #radius: radius,
          },
        ),
        returnValue:
            _i5.Future<List<_i3.PharmacyModel>>.value(<_i3.PharmacyModel>[]),
      ) as _i5.Future<List<_i3.PharmacyModel>>);

  @override
  _i5.Future<List<_i3.PharmacyModel>> getOnDutyPharmacies({
    double? latitude,
    double? longitude,
    double? radius,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getOnDutyPharmacies,
          [],
          {
            #latitude: latitude,
            #longitude: longitude,
            #radius: radius,
          },
        ),
        returnValue:
            _i5.Future<List<_i3.PharmacyModel>>.value(<_i3.PharmacyModel>[]),
      ) as _i5.Future<List<_i3.PharmacyModel>>);

  @override
  _i5.Future<_i3.PharmacyModel> getPharmacyDetails(int? pharmacyId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPharmacyDetails,
          [pharmacyId],
        ),
        returnValue: _i5.Future<_i3.PharmacyModel>.value(_FakePharmacyModel_1(
          this,
          Invocation.method(
            #getPharmacyDetails,
            [pharmacyId],
          ),
        )),
      ) as _i5.Future<_i3.PharmacyModel>);

  @override
  _i5.Future<List<_i3.PharmacyModel>> getFeaturedPharmacies() =>
      (super.noSuchMethod(
        Invocation.method(
          #getFeaturedPharmacies,
          [],
        ),
        returnValue:
            _i5.Future<List<_i3.PharmacyModel>>.value(<_i3.PharmacyModel>[]),
      ) as _i5.Future<List<_i3.PharmacyModel>>);
}
