// Mocks generated by Mockito 5.4.4 from annotations
// in drpharma_client/test/features/products/data/repositories/products_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:drpharma_client/core/network/api_client.dart' as _i2;
import 'package:drpharma_client/features/products/data/datasources/products_local_datasource.dart'
    as _i6;
import 'package:drpharma_client/features/products/data/datasources/products_remote_datasource.dart'
    as _i4;
import 'package:drpharma_client/features/products/data/models/product_model.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeApiClient_0 extends _i1.SmartFake implements _i2.ApiClient {
  _FakeApiClient_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeProductModel_1 extends _i1.SmartFake implements _i3.ProductModel {
  _FakeProductModel_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ProductsRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductsRemoteDataSource extends _i1.Mock
    implements _i4.ProductsRemoteDataSource {
  MockProductsRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ApiClient get apiClient => (super.noSuchMethod(
        Invocation.getter(#apiClient),
        returnValue: _FakeApiClient_0(
          this,
          Invocation.getter(#apiClient),
        ),
      ) as _i2.ApiClient);

  @override
  _i5.Future<List<_i3.ProductModel>> getProducts({
    int? page = 1,
    int? perPage = 20,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProducts,
          [],
          {
            #page: page,
            #perPage: perPage,
          },
        ),
        returnValue:
            _i5.Future<List<_i3.ProductModel>>.value(<_i3.ProductModel>[]),
      ) as _i5.Future<List<_i3.ProductModel>>);

  @override
  _i5.Future<_i3.ProductModel> getProductDetails(int? productId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProductDetails,
          [productId],
        ),
        returnValue: _i5.Future<_i3.ProductModel>.value(_FakeProductModel_1(
          this,
          Invocation.method(
            #getProductDetails,
            [productId],
          ),
        )),
      ) as _i5.Future<_i3.ProductModel>);

  @override
  _i5.Future<List<_i3.ProductModel>> searchProducts({
    required String? query,
    int? page = 1,
    int? perPage = 20,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchProducts,
          [],
          {
            #query: query,
            #page: page,
            #perPage: perPage,
          },
        ),
        returnValue:
            _i5.Future<List<_i3.ProductModel>>.value(<_i3.ProductModel>[]),
      ) as _i5.Future<List<_i3.ProductModel>>);

  @override
  _i5.Future<List<_i3.ProductModel>> getProductsByCategory({
    required String? category,
    int? page = 1,
    int? perPage = 20,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProductsByCategory,
          [],
          {
            #category: category,
            #page: page,
            #perPage: perPage,
          },
        ),
        returnValue:
            _i5.Future<List<_i3.ProductModel>>.value(<_i3.ProductModel>[]),
      ) as _i5.Future<List<_i3.ProductModel>>);

  @override
  _i5.Future<List<_i3.ProductModel>> getProductsByPharmacy({
    required int? pharmacyId,
    int? page = 1,
    int? perPage = 20,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProductsByPharmacy,
          [],
          {
            #pharmacyId: pharmacyId,
            #page: page,
            #perPage: perPage,
          },
        ),
        returnValue:
            _i5.Future<List<_i3.ProductModel>>.value(<_i3.ProductModel>[]),
      ) as _i5.Future<List<_i3.ProductModel>>);
}

/// A class which mocks [ProductsLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductsLocalDataSource extends _i1.Mock
    implements _i6.ProductsLocalDataSource {
  MockProductsLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<void> cacheProducts(List<_i3.ProductModel>? products) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheProducts,
          [products],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<List<_i3.ProductModel>?> getCachedProducts() =>
      (super.noSuchMethod(
        Invocation.method(
          #getCachedProducts,
          [],
        ),
        returnValue: _i5.Future<List<_i3.ProductModel>?>.value(),
      ) as _i5.Future<List<_i3.ProductModel>?>);

  @override
  _i5.Future<void> cacheProductDetails(_i3.ProductModel? product) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheProductDetails,
          [product],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i3.ProductModel?> getCachedProductDetails(int? productId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCachedProductDetails,
          [productId],
        ),
        returnValue: _i5.Future<_i3.ProductModel?>.value(),
      ) as _i5.Future<_i3.ProductModel?>);
}
