// Mocks generated by Mockito 5.4.4 from annotations
// in drpharma_client/test/features/notifications/presentation/providers/notifications_notifier_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:dartz/dartz.dart' as _i3;
import 'package:drpharma_client/core/errors/failures.dart' as _i7;
import 'package:drpharma_client/core/network/api_client.dart' as _i4;
import 'package:drpharma_client/features/notifications/data/datasources/notifications_remote_datasource.dart'
    as _i11;
import 'package:drpharma_client/features/notifications/data/models/notification_model.dart'
    as _i12;
import 'package:drpharma_client/features/notifications/domain/entities/notification_entity.dart'
    as _i8;
import 'package:drpharma_client/features/notifications/domain/repositories/notifications_repository.dart'
    as _i2;
import 'package:drpharma_client/features/notifications/domain/usecases/get_notifications_usecase.dart'
    as _i5;
import 'package:drpharma_client/features/notifications/domain/usecases/mark_all_notifications_read_usecase.dart'
    as _i10;
import 'package:drpharma_client/features/notifications/domain/usecases/mark_notification_read_usecase.dart'
    as _i9;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeNotificationsRepository_0 extends _i1.SmartFake
    implements _i2.NotificationsRepository {
  _FakeNotificationsRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeApiClient_2 extends _i1.SmartFake implements _i4.ApiClient {
  _FakeApiClient_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetNotificationsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetNotificationsUseCase extends _i1.Mock
    implements _i5.GetNotificationsUseCase {
  MockGetNotificationsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.NotificationsRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeNotificationsRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.NotificationsRepository);

  @override
  _i6.Future<_i3.Either<_i7.Failure, List<_i8.NotificationEntity>>> call() =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue: _i6.Future<
                _i3.Either<_i7.Failure, List<_i8.NotificationEntity>>>.value(
            _FakeEither_1<_i7.Failure, List<_i8.NotificationEntity>>(
          this,
          Invocation.method(
            #call,
            [],
          ),
        )),
      ) as _i6.Future<_i3.Either<_i7.Failure, List<_i8.NotificationEntity>>>);
}

/// A class which mocks [MarkNotificationAsReadUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockMarkNotificationAsReadUseCase extends _i1.Mock
    implements _i9.MarkNotificationAsReadUseCase {
  MockMarkNotificationAsReadUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.NotificationsRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeNotificationsRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.NotificationsRepository);

  @override
  _i6.Future<_i3.Either<_i7.Failure, void>> call(String? notificationId) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [notificationId],
        ),
        returnValue: _i6.Future<_i3.Either<_i7.Failure, void>>.value(
            _FakeEither_1<_i7.Failure, void>(
          this,
          Invocation.method(
            #call,
            [notificationId],
          ),
        )),
      ) as _i6.Future<_i3.Either<_i7.Failure, void>>);
}

/// A class which mocks [MarkAllNotificationsReadUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockMarkAllNotificationsReadUseCase extends _i1.Mock
    implements _i10.MarkAllNotificationsReadUseCase {
  MockMarkAllNotificationsReadUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.NotificationsRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeNotificationsRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.NotificationsRepository);

  @override
  _i6.Future<_i3.Either<_i7.Failure, void>> call() => (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue: _i6.Future<_i3.Either<_i7.Failure, void>>.value(
            _FakeEither_1<_i7.Failure, void>(
          this,
          Invocation.method(
            #call,
            [],
          ),
        )),
      ) as _i6.Future<_i3.Either<_i7.Failure, void>>);
}

/// A class which mocks [NotificationsRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockNotificationsRemoteDataSource extends _i1.Mock
    implements _i11.NotificationsRemoteDataSource {
  MockNotificationsRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.ApiClient get apiClient => (super.noSuchMethod(
        Invocation.getter(#apiClient),
        returnValue: _FakeApiClient_2(
          this,
          Invocation.getter(#apiClient),
        ),
      ) as _i4.ApiClient);

  @override
  _i6.Future<List<_i12.NotificationModel>> getNotifications() =>
      (super.noSuchMethod(
        Invocation.method(
          #getNotifications,
          [],
        ),
        returnValue: _i6.Future<List<_i12.NotificationModel>>.value(
            <_i12.NotificationModel>[]),
      ) as _i6.Future<List<_i12.NotificationModel>>);

  @override
  _i6.Future<void> markAsRead(String? notificationId) => (super.noSuchMethod(
        Invocation.method(
          #markAsRead,
          [notificationId],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> markAllAsRead() => (super.noSuchMethod(
        Invocation.method(
          #markAllAsRead,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> deleteNotification(String? notificationId) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteNotification,
          [notificationId],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> updateFcmToken(String? token) => (super.noSuchMethod(
        Invocation.method(
          #updateFcmToken,
          [token],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> removeFcmToken() => (super.noSuchMethod(
        Invocation.method(
          #removeFcmToken,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);
}
