# DR-PHARMA Courier - Keystore Configuration
# NE PAS COMMITER CE FICHIER DANS GIT !
# Ajoutez-le à votre .gitignore

storePassword=DrPharma2026
keyPassword=DrPharma2026
keyAlias=drpharma-courier
storeFile=../keystores/drpharma-courier.keystore
